Product list paging
Java-DZGS/ingreedio pull request #77
Opened 2024-05-29 14:06 UTC by GitQueenZofia

2024-05-30 14:32 UTC, andrmdmd requested changes

2024-05-30 14:32 UTC, andrmdmd commented on src/components/ProductListScrollBar/ProductListScrollBar.tsx
> +const ProductListScrollBar = ({
I think the name should be more generic, maybe `PagingScrollBar`?

2024-05-30 14:32 UTC, andrmdmd commented on src/components/ProductListScrollBar/ProductListScrollBar.tsx
> +import React, { ReactNode, useCallback } from 'react';
linting

2024-05-30 14:32 UTC, andrmdmd commented on package.json
> +    "react-spinners": "^0.13.8",
are we using both?

2024-05-30 14:32 UTC, andrmdmd commented on src/components/ProductListScrollBar/ProductListScrollBar.tsx
> +    if (distanceFromBottom < 50) {
I tested it with a few values and i thing something like `300` here has a better feel

2024-05-30 15:16 UTC, andrmdmd commented on src/components/ProductListScrollBar/ProductListScrollBar.tsx
> +    console.log(distanceFromBottom);
I think it is a leftover debugging log

2024-05-31 20:46 UTC, andrmdmd approved these changes

2024-05-31 20:52 UTC, andrmdmd commented
GJ!

2024-06-02 14:04 UTC, mslup approved these changes

2024-06-02 14:04 UTC, merged